I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_jenya_ch1.rpy", line 609, in script
    "Какие же неожиданные гады! Какая мерзость! Неужели я когда-то смогу к этому привыкнуть?"
OSError: Couldn't find file 'audio/sounds/screamer2.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_jenya_ch1.rpy", line 609, in script
    "Какие же неожиданные гады! Какая мерзость! Неужели я когда-то смогу к этому привыкнуть?"
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\display\core.py", line 3587, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\display\core.py", line 4107, in interact_core
    renpy.audio.audio.interact()
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\audio\audio.py", line 1271, in interact
    periodic()
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\audio\audio.py", line 1224, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\audio\audio.py", line 1202, in periodic_thread_main
    periodic_pass()
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\audio\audio.py", line 1144, in periodic_pass
    c.periodic()
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio/sounds/screamer2.mp3'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
Ты не один 0.1
Sun Mar 23 18:39:16 2025
